### PR TITLE
Object fields containing objects may not return proper object value in certain circumstances.

### PR DESCRIPTION
**Pull request by Arkatufus**
Fix for #89 and #92

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
Weird... wonder why Azure Pipelines didn't pick this up

**Comment by Aaronontheweb** [comment]
Ah, looks like Github credentials expired as we're on an "old" version of Azure Pipelines, compared to what Akka.NET itself uses. I'll get that swapped out.

**Comment by Aaronontheweb** [comment]
@Arkatufus queued these up manually inside Azure Pipelines. Should all be automatic now moving forward. Old Github credentials expired because I set them up with OAuth originally. Went back to using the Github App authentication method.

**Comment by Aaronontheweb** [comment]
CI passed but didn't push any of its checks

**Comment by Arkatufus** [comment]
OK, thanks man.

**Pull request merged**
