### PR TITLE
Overloads with values for HoconRoot getters

### PR DESCRIPTION
**Pull request by IgorFedchenko**
Related to #108

First, existing overloads like `obj.GetDouble("a", @default: 5)` did not work, because it was expecting underlying `GetNode` to return `null` when path was not found, but it was throwing exception (which is generally good thing, but here needed to catch it).

Second - there was no way to specify default value for collection getters (i.e. if I want to get empty list of ids if they are not set - the only options was to handle exception). Added this overloads, and added test for all of them.

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
`Hocon.Tests.HoconTests.GettingArrayFromLiteralsReturnsNull` - have a failure on this spec.

**Comment by Aaronontheweb** [comment]
(I still don't know why Azure DevOps isn't showing status for PRs in this repository - only shows status for code once it's directly merged into `dev`)

**Comment by IgorFedchenko** [comment]
> `Hocon.Tests.HoconTests.GettingArrayFromLiteralsReturnsNull` - have a failure on this spec.

Yup, the behavior asserted in this test was incorrect actually, so fixed it too

**Comment by Aaronontheweb** [comment]
@IgorFedchenko looks like the CI system is not our friend still

**Comment by IgorFedchenko** [comment]
> @IgorFedchenko looks like the CI system is not our friend still

@Aaronontheweb Yup... In Akka.NET also not all steps are completed. Looking at issue [here](https://developercommunity.visualstudio.com/content/problem/858369/github-status-suddenly-stopped-displaying-for-pull.html), they still did not resolve this problem.

**Comment by Aaronontheweb** [comment]
`Hocon.Extensions.Configuration.Tests.ConfigurationSpec.ShouldReloadConfigurationOnFileChange` failed - this test seems to be pretty racy (has a high flip rate on Azure DevOps.) I'll take a look at it.

**Comment by Aaronontheweb** [comment]
@IgorFedchenko have a merge conflict here

**Comment by IgorFedchenko** [comment]
> @IgorFedchenko have a merge conflict here

Since https://github.com/akkadotnet/HOCON/pull/148 was based in this PR, the changes are already in dev branch, and #148 overwrites some of them. 
Anyway, resolved conflicts now, should be ready for merge.

**Comment by Aaronontheweb** [comment]
Thanks @IgorFedchenko

**Pull request merged**
