### PR TITLE
Dnx

### PR DESCRIPTION
**Pull request by adamhathcock**
My hobby is doing DNX conversions apparently.

All the tests and demos work, except the one reading from app.config as under DNX this doesn't work even for full .NET.

I added Hocon source for Microsoft.Framework.Configuration to integate with it with a demo project.

### CODE REVIEW

**Comment by haighis** [comment]
Can you provide rational for using xunit over nunit for the test framework?

**Comment by haighis** [comment]
Have you discussed using DNX for Hocon with @Aaronontheweb  or @rogeralsing?

**Comment by haighis** [comment]
Also the build is failing so I don't think this can be merged until the build passes.

**Comment by adamhathcock** [comment]
Sorry, I probably should have made an issue instead of a PR as this is a big deal to switch and I know the decision hasn't been made yet.

Xunit is the only cross platform testing framework at the moment.

This library could probably target "dotnet" to be more lightweight.

**Comment by rogeralsing** [comment]
I think we can work with this, we have a ticket on the main repo to move Akka.NET to dnx also, but nothing have been decided yet.
regarding xUnit vs nUnit, Im open for anything here, xUnit have caused us problems in the past, but if nUnit doesnt even work on mono I guess we have no choise.

leave this open and work with the tests and I will bring this up with the others on the core team

**Comment by adamhathcock** [comment]
By Cross platform I mean DNX support in xunit.  Just curious, what issues have you had with xunit?

At work, we switched to xunit from mstest and nunit for DNX.  (I thought nunit too old anyway.)

I recognize you can use project.json without dnx and netcore support but I'm hoping to get some in anyway :). Linux support is a big thing for me and mono has never felt viable.

**Comment by sean-gilliam** [comment]
Closing this issue due to linked PR superseding this.

**Pull request closed without merging**
