### PR TITLE
Parsing improvements, spec conformation, better parsing exception message

### PR DESCRIPTION
**Pull request by Arkatufus**
Added line number and position to parsing exceptions
Fix parsing to conform with substitution handling spec and error spec

### CODE REVIEW

**Comment by Arkatufus** [comment]
The parser is a lot more strict now:
- Opening and closing braces have to match, mismatched braces will throw.
- Mixing string literal, array, and object in a value concatenation (in a single line) will throw.
- Objects can be merged through substitution (inheritance), it was ignored before the fix.
- Calling Config.GetValue(path) with a non existent path returns a HoconValue.Undefined instead of a null.
- Calling any list/array getter methods with a non existent path will throw, it either throws a LINQ exception or an empty array before the fix.
- All of whitespaces defined in the HOCON spec is supported, all of these whitespace characters are preserved if they are defined between two literal definition.

**Comment by Aaronontheweb** [comment]
@Arkatufus so, how do we rebase on this on top of your parser rewrite? :p

**Comment by Arkatufus** [comment]
Just trash this PR, its all covered by the complete rewrite

**Comment by Aaronontheweb** [comment]
@Arkatufus done

**Pull request closed without merging**
