### PR TITLE
Split test files to match HOCON spec document headings to simplify spec conformation

### PR DESCRIPTION
**Pull request by Arkatufus**
Progress:
- [x] Comments
- [x] Omit root braces
- [x] Key-value separator
- [x] Commas
- [x] Whitespace
- [x] Duplicate keys and object merging
- [x] Unquoted strings
- [x] Multi-line strings
- [x] Value concatenation - String
- [x] Value concatenation - Object
  - Might need to find a better way to merge objects to prevent unwanted side effects.
- [x] Path expressions
- [x] Path as keys
- [x] Substitutions - Normal
- [x] Substitutions - Self-Referential
- [x] += field separator
- [x] Includes - Merging
- [x] Includes - Substitution
- [x] Includes - Missing files and required files
- Includes - File formats and extensions
  - Not implemented because file loading functionality are not the responsibility of the parser, but delegated to a callback function.
- [x] Includes - Locating resources
- [x] Conversion of numerically-indexed objects to arrays
  - Also need to find a better way to enumerate over array of objects
- [x] Automatic type conversions
- [x] Unit format
  - [x] Duration format
  - Period format
    - .Net does not have a concept/implementation for java.time.Period (abstraction of time span into days/months/years)
  - [x] Size in bytes format
    - Byte sizes above exabyte (zetta and yotta) are not supported because of long overflow problem. To fix this, we would need to change this property accessor to return BigInteger instead of long.

### CODE REVIEW

**Comment by Arkatufus** [comment]
Don't merge

**Comment by Aaronontheweb** [comment]
@Arkatufus updated this PR with the latest.

**Comment by Aaronontheweb** [comment]
@Arkatufus just waiting on the last thing?

**Comment by Arkatufus** [comment]
@Aaronontheweb yes, just one tick left to implement. Any preference on the byte size format accessor? Should we change it to BigInteger?

**Comment by Aaronontheweb** [comment]
>  Any preference on the byte size format accessor? Should we change it to BigInteger?

I'm not sure I understand the question - what are the implications?

**Comment by Arkatufus** [comment]
@Aaronontheweb Byte size unit format can easily express byte values that overflows a 64-bit integer if not carefully used. BigInteger mitigates that, but makes the API harder to use, since users usually expect a Long, and are forced to do manual conversion every time they use GetBytes().

**Comment by Aaronontheweb** [comment]
@Arkatufus 

> Byte size unit format can easily express byte values that overflows a 64-bit integer

So this would be in the case that a user expresses some object that is larger than 2^64 bytes?

**Comment by Arkatufus** [comment]
@Aaronontheweb Yes, a typo in the exbibyte size can do that because its so close to 2^64 already. (I think) We haven't reached this limit in computing, yet, though it might happen in data centers in the foreseeable future?

**Comment by Aaronontheweb** [comment]
I'm sure it'll happen in the future, but I think we should stick with `long` because otherwise that'll force all of our downstream dependencies that need access to byte size descriptors to start using `BigInteger` too, no?

**Comment by Arkatufus** [comment]
@Aaronontheweb good point, we'll leave it as `long` for now.

**Comment by Aaronontheweb** [comment]
Good deal, let me know when this is ready for merging / review

**Comment by Arkatufus** [comment]
#86 is the last tick, just need a review for that

**Comment by Aaronontheweb** [comment]
Nice work. We should get prepared for another HOCON release.

**Pull request merged**
